import './assets/css/normalize.css';
import './assets/css/blog.css';
import './assets/css/prettify.css';
import '@fortawesome/fontawesome-free/js/fontawesome';
import '@fortawesome/fontawesome-free/js/solid';
import '@fortawesome/fontawesome-free/js/regular';
import '@fortawesome/fontawesome-free/js/brands';

var $ = require('./assets/js/jquery-3.4.1.min.js');
window.$ = $;
window.jQuery = $;
var _ = require('./assets/js/underscore.js');
window._ = _;
window.underscore = _;
require('./assets/js/jquery-stickyNavigator.js');
require('./assets/js/jquery-isystkOverlay.js');
require('./assets/js/jquery-isystkSlider.js');
require('./assets/js/jquery-zoomSlider.js');
require('./assets/js/prettify.js');
require('./assets/js/lang-css.js');
require('./assets/js/blog.js');
